version: '3'
services:
  trivicord:
    image: refractix/trivicord
    environment:
      DB_TYPE: "mongodb"
      DB_URI: "mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo"
      DISCORD_TOKEN: "${DISCORD_TOKEN}"

  mongo:
    image: mongo
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"

volumes:
  mongo_volume: